#+TITLE: Card Updates
#+AUTHOR: Devin M. O'Brien

* Document
** Purpose
This document is to help keep track of development as we move
forward. Everything in the overview will essentially be the same so
you can move to [[Updates]] for information on what is actually going
on. 

** Conventions
*** Org-Mode
This document is a plain text file that uses
[[https://orgmode.org/][Org Mode]] which is, on a basic level, a schema that is similar to
markdown. In truth, that doesn't give it justice since its
implementation is more powerful than any markdown implementation that
I have seen. 
*** Emacs
I am using [[https://www.gnu.org/software/emacs/][emacs]] to edit the the document. Emacs is a powerful
text-editor which does translate to it being difficult to use so I
don't expect anyone else to use it. If you would like me to describe
the problems with it, I can add a list, but otherwise I will leave
that open-ended.
*** Task Management
With [[Org-Mode]], I can implemnt some task management through [[https://orgmode.org/manual/TODO-dependencies.html#TODO-dependencies][TODO]] (not
great example, but easiest to look at) and tags which I may do moving
forward.

Should I do this, the copy that you to look at would be in the main
branch. 

* Updates
** Description
This will contain two types of items, things that have been completed
and what needs to be done. 


#+TAGS: @devin(d) @sage(s) @jake(j)
#+TODO: TODO WORKING-ON | DONE
#+TODO REPORT BUG KNOWNCAUSE WORKING-ON | FIXED

** TODO Finish Updates.org                                           :@devin:
** TODO Standardize Directory Structure
*** WORKING-ON Gradle Not Working                                    :@devin:
    :DESCRIPTION:
    The fix that I have is to remake the entire project
    this will probably cause some conflicts. 
    :END:
*** TODO Add JavaFX
** TODO Finish Mock-ups
** TODO Finish SRD 
