/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Cards.app;


import Cards.controllers.CardViewController.CardViewController;
import Cards.models.Card;
import Cards.models.HTMLMod;
import Cards.models.HTMLModel;
import Cards.views.CardView;
import org.w3c.dom.html.HTMLDocument;
import Cards.models.CardLogger;

import static Cards.models.CardLogger.logg;
import static Cards.models.CardLogger.logger_setup;

public class App {


    /**
     * Starting Point
     *
     * @param args
     */
    public static void main(String[] args) {
        /**
         * Desired Flow:
         *  \-> Create App Model
         *      \-> If Setup(TRUE) -> Start
     *          \-> If Setup(FALSE) -> Setup
         *
         */



        logger_setup(); // This sets up  the logger; only needed here
        logg.fine("Logger has been setup");
        

        HTMLMod x = new HTMLMod("/Test.html");

        CardView card = new CardView(x.toString());
        System.out.println(x.toString());

        card.show();
        logg.fine("Exiting Program");
    }
}
