/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Cards.app;


import Cards.controllers.CardViewController.CardViewController;
import Cards.models.HTMLModel;
import org.w3c.dom.html.HTMLDocument;

public class App{


    public static void main(String[] args) {

       // JavaFXController red = new JavaFXController();
      //  red.show();


       CardViewController card = new CardViewController();
        card.show();
    }
}
