/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Cards.app;


public class App{


    public static void main(String[] args) {

        JavaFXController red = new JavaFXController();
        red.show();
    }
}
