/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Cards.app;
// TODO Remove
class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
