/*
 * This Java source file was generated by the Gradle 'init' task.
 *
 *  This is not used except by gradle
 */
package Cards.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
